from django.conf.urls import url
from . import views

urlpatterns = [
    url('^$', views.mainRender, name='mainRender'),
    url('boxWrapper', views.boxWrapperRender, name='boxWrapperRender'),
    url('boxTourRender', views.boxTourRender, name='boxTourRender'),
    url('boxAgeRender', views.boxAgeRender, name='boxAgeRender'),
    url('boxLitRender', views.boxLitRender, name='boxLitRender'),
    url('boxGdpRender', views.boxGdpRender, name='boxGdpRender'),
    url('boxTempRender', views.boxTempRender, name='boxTempRender'),
    url('boxPopRender', views.boxPopRender, name='boxPopRender'),
    url('boxTour', views.boxTour, name='boxTour'),
    url('boxAge', views.boxAge, name='boxAge'),
    url('boxLit', views.boxLit, name='boxLit'),
    url('boxGdp', views.boxGdp, name='boxGdp'),
    url('boxTemp', views.boxTemp, name='boxTemp'),
    url('boxPop', views.boxPop, name='boxPop'),

    url('lineWrapper', views.lineWrapperRender, name='lineWrapperRender'),
    url('lineTourRender', views.lineTourRender, name='lineTourRender'),
    url('lineAgeRender', views.lineAgeRender, name='lineAgeRender'),
    url('lineLitRender', views.lineLitRender, name='lineLitRender'),
    url('lineGdpRender', views.lineGdpRender, name='lineGdpRender'),
    url('lineTempRender', views.lineTempRender, name='lineTempRender'),
    url('linePopRender', views.linePopRender, name='linePopRender'),
    url('lineTourRender', views.lineTourRender, name='lineTourRender'),
    url('lineTour', views.lineTour, name='lineTour'),
    url('lineAge', views.lineAge, name='lineAge'),
    url('lineLit', views.lineLit, name='lineLit'),
    url('lineGdp', views.lineGdp, name='lineGdp'),
    url('lineTemp', views.lineTemp, name='lineTemp'),
    url('linePop', views.linePop, name='linePop'),
    url('lineTour', views.lineTour, name='lineTour'),

    url('histWrapper', views.histWrapperRender, name='histWrapperRender'),
    url('histTourRender', views.histTourRender, name='histTourRender'),
    url('histAgeRender', views.histAgeRender, name='histAgeRender'),
    url('histLitRender', views.histLitRender, name='histLitRender'),
    url('histGdpRender', views.histGdpRender, name='histGdpRender'),
    url('histTempRender', views.histTempRender, name='histTempRender'),
    url('histPopRender', views.histPopRender, name='histPopRender'),
    url('histTourRender', views.histTourRender, name='histTourRender'),
    url('histTour', views.histTour, name='histTour'),
    url('histAge', views.histAge, name='histAge'),
    url('histLit', views.histLit, name='histLit'),
    url('histGdp', views.histGdp, name='histGdp'),
    url('histTemp', views.histTemp, name='histTemp'),
    url('histPop', views.histPop, name='histPop'),
    url('histTour', views.histTour, name='histTour'),

    url('seaPlot', views.seaPlot, name='seaPlot'),
    url('snsRender', views.snsRender, name='snsRender'),

]